version: "3.9"
services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: "data"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"